setwd("D:\\kaggle\\R")
library(rpart)
train <-read.csv('D:\\kaggle\\datasets\\train.csv')
test <-read.csv('D:\\kaggle\\datasets\\test.csv')
summary(train)
fit<-rpart(Survived~ Pclass + Sex + Age +SibSp + Parch + Fare +Embarked ,data = train,method = "class",control = rpart.control(minsplit = 2,cp=0))
library(rattle)
library(rpart.plot)
library(RColorBrewer)
fancyRpartPlot(fit)
pridiction<-predict(fit,test,type = "class")
submit<-data.frame(PassengerId=test$PassengerId,survived=pridiction)
write.csv(submit,file="mysecondtree.csv",row.names = FALSE)
